Repository tmphat1312/movred, pull requests merged in 2025-01, with the labels that each got.

#48 chore: upgrade next and react to the latest version
  package-lock.json
  package.json
Labels: good first issue

#52 23 overall information header footer (close #23)
  src/components/authentication-status.tsx
  src/components/fancy-logo.tsx
  src/components/gradient-link.tsx
  src/components/layouts/dashboard-header.tsx
  src/components/layouts/footer.tsx
  src/components/layouts/home-header.tsx
  src/components/layouts/main-navigation.tsx
  src/components/layouts/sticky-header.tsx
  src/components/logo.tsx
  src/components/sign-out-button.tsx
Labels: enhancement

#57 ui: add loading fallback to latest trailers
  src/features/latest-trailers/components/latest-trailers-section.tsx
  src/features/latest-trailers/components/latest-trailers.tsx
Labels: enhancement

#58 Search panel
  public/images/hero-section/1.webp
  public/images/hero-section/2.webp
  public/images/hero-section/3.webp
  public/images/hero-section/4.webp
  src/app/page.tsx
  src/components/section-placeholder.tsx
  src/features/home/components/search-hero-section.tsx
  src/features/home/components/search-movie-form.tsx
  src/lib/utils/number-helpers.ts
Labels: enhancement

#62 Cast quick infor
  src/app/globals.css
  src/app/loading.tsx
  src/app/movies/[id]/loading.tsx
  src/app/people/[id]/page.tsx
  src/constants/gender.ts
  src/features/cast-details/banner.tsx
  src/features/cast-details/components/biography.tsx
  src/features/cast-details/components/main-reading.tsx
  src/features/cast-details/components/outline-dot.tsx
  src/features/cast-details/components/personal-information.tsx
  src/features/cast-details/data/get-cast-details.ts
  src/features/cast-details/data/get-cast-movie-credits.ts
Labels: enhancement, UX

#64 Fix/use params suspense
  src/features/search-movies/data/get-search-results.ts
  src/features/trending-movies/components/trending-movies-section.tsx
Labels: bug

#65 Movie links and keywords
  package-lock.json
  package.json
  src/features/movie-details/components/keywords.tsx
  src/features/movie-details/components/more-information.tsx
  src/features/movie-details/components/social-links.tsx
  src/features/movie-details/data/get-external-ids.ts
  src/features/movie-details/data/get-movie-keywords.ts
  src/types/utilities.ts
Labels: enhancement

#68 61 no casts
  src/features/movie-details/components/casts.tsx
  src/features/movie-details/components/recommendations.tsx
Labels: bug

#71 ui: draft the play trailer modal ui
  src/features/latest-trailers/data/get-latest-trailers.tsx
  src/features/movie-details/components/play-modal-button.tsx
  src/features/movie-details/components/play-trailer-modal.tsx
  src/features/movie-details/components/quick-information.tsx
  src/features/movie-details/components/user-actions.tsx
Labels: enhancement

#76 Reviews
  src/app/(content)/movies/[id]/page.tsx
  src/app/(content)/page.tsx
  src/app/(content)/profile/page.tsx
  src/data/schema.ts
  src/features/home/components/create-our-user.tsx
  src/features/home/data/create-our-user.ts
  src/features/home/data/find-user-by-clerk-id.ts
  src/features/home/data/update-our-user.ts
  src/features/movie-details/actions/post-a-review.ts
  src/features/movie-details/components/review-form.tsx
  src/features/movie-details/components/review-list.tsx
  src/features/movie-details/components/your-review.tsx
  src/features/movie-details/data/add-to-watch-list.ts
  src/features/movie-details/data/find-your-review.ts
  src/features/movie-details/data/get-movie-reviews.ts
  src/features/movie-details/data/is-movie-in-your-favorite-list.ts
  src/features/movie-details/data/is-movie-in-your-watch-list.ts
  src/features/movie-details/data/mark-as-favorite.ts
  src/features/movie-details/data/post-a-review.ts
  src/features/movie-details/data/rate-a-movie.ts
  src/features/user-profile/components/favorite-list.tsx
  src/features/user-profile/components/greeting.tsx
  src/features/user-profile/components/rating-list.tsx
  src/features/user-profile/components/watch-list.tsx
  src/features/user-profile/data/get-favorite-list.ts
  src/features/user-profile/data/get-rating-list.ts
  src/features/user-profile/data/get-watch-list.ts
  src/lib/data/get-internal-user.ts
Labels: enhancement

#83 Filtering
  src/app/(content)/search/page.tsx
  src/features/movie-details/components/keywords.tsx
  src/features/search-movies/components/filter-form.tsx
  src/features/search-movies/components/search-results.tsx
  src/features/search-movies/components/sort-form.tsx
  src/features/search-movies/data/get-search-results.ts
Labels: enhancement

#84 Migrate db
  src/data/__port-data.ts
  src/data/__scape-data.ts
  src/data/schema.ts
Labels: enhancement

#86 Decoration
  package-lock.json
  package.json
  src/components/movie-card.tsx
  src/components/ui/scale-slider.tsx
  src/data/__port-data.ts
  src/data/__scrape-data.ts
  src/data/import_data.ts
  src/data/schema.ts
  src/features/cast-details/components/main-reading.tsx
  src/features/cast-details/components/personal-information.tsx
  src/features/home/components/create-our-user.tsx
  src/features/home/components/search-hero-section.tsx
  src/features/home/data/create-our-user.ts
  src/features/latest-trailers/components/trailer-card.tsx
  src/features/latest-trailers/data/get-latest-trailers.tsx
  src/features/movie-details/components/quick-information.tsx
  src/features/movie-details/components/recommendations.tsx
  src/features/movie-details/components/user-actions.tsx
  src/features/movie-details/data/find-your-rating.ts
  src/features/movie-details/data/get-movie-recommendations.ts
  src/features/movie-details/data/post-a-rating.ts
  src/features/popular-movies/data/get-popular-movies.ts
  src/features/user-profile/components/move-poster-card.tsx
  src/features/user-profile/components/movie-backdrop-card.tsx
  src/features/user-profile/data/remove-from-rating-list.ts
  tailwind.config.ts
Labels: enhancement

#92 fix: resolve edit timeout
  package.json
Labels: bug
